//
// Autogenerated by Thrift Compiler (0.23.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');


declare enum ResearchItemType {
  REPOSITORY = 1,
  DATASET = 2,
  MODEL = 3,
  NOTEBOOK = 4,
}

declare class ResearchItem {
  public id: string;
  public title: string;
  public description: string;
  public type: ResearchItemType;
  public tags: string[];
  public authors: string[];
  public createdAt: string;
  public updatedAt: string;

    constructor(args?: { id: string; title: string; description: string; type: ResearchItemType; tags: string[]; authors: string[]; createdAt: string; updatedAt: string; });
}

declare class CatalogFilter {
  public type?: ResearchItemType;
  public tags?: string[];
  public searchQuery?: string;

    constructor(args?: { type?: ResearchItemType; tags?: string[]; searchQuery?: string; });
}
